package com.supermap.desktop.enums;

public enum XMLCommandType {

	RIBBON,
    COMMAND,
    BUTTON,
    BOX,
    BUTTONDROPDOWN,
    CHECKBOX,
    COLORBUTTON,
    COMBOBOX,
    GALLERY,
    GALLERYITEM,
    GALLERYITEMGROUP,
    INTEGERUPDOWN,
    LABEL,
    SEPARATOR,
    TEXTBOX,
    DIALOGBOXLAUNCHER,
    COMBOBOXITEM,
    GROUP,
    RIBBONTAB,
    CONTEXTUALTAB,

    FRAMEMENUS,
    FRAMEMENU,    
    CONTEXTMENUS,
    CONTEXTMENU,    
    MENUGROUP,    
    MENUBUTTON,
    MENUBUTTONDROPDOWN,
    
    TOOLBARS,
    TOOLBAR,

    DOCKBARS,
    DOCKBAR,
    DOCKBARGROUP,

    STARTMENU,
    BACKSTAGETAB,
    BACKSTAGEBUTTONDROPDOWN,

    STATUSBARS,
    STATUSBAR,

    USERCONTROL; // 暂未开放      
}