<!-- GitHub Star -->
<!--<iframe src="https://ghbtns.com/github-btn.html?user=qinlj&repo=iDesktop-Cross-Docs&type=star&count=true" frameborder="0" scrolling="0" width="110px" height="20px"></iframe>-->
<!-- GitHub fork -->
<!--<iframe src="https://ghbtns.com/github-btn.html?user=qinlj&repo=iDesktop-Cross-Docs&type=fork&count=true" frameborder="0" scrolling="0" width="110px" height="20px"></iframe>-->
<!-- Tweet button -->
<!--a href="https://twitter.com/share" class="twitter-share-button" data-url="http://hexo.io/" data-text="SuperMap iDesktop Cross 9D  -- 一款支持跨平台的桌面GIS应用与开发平台，超图新一代的开源GIS桌面产品" data-hashtags="hexo,nodejs">Tweet</a-->
<!-- Twitter follow button -->
<!-- a href="http://git.oschina.net/supermap/SuperMap-iDesktop-Cross" class="twitter-follow-button" data-show-count="false">关注 @SuperMapCross</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script-->